//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Llis.Data.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class llisdb : DbContext
    {
        public llisdb()
            : base("name=llisdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserAccountOperation> UserAccountOperations { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<UserDepartmentOperation> UserDepartmentOperations { get; set; }
        public DbSet<UserDepartment> UserDepartments { get; set; }
        public DbSet<UserAccountsView> UserAccountsViews { get; set; }
        public DbSet<UserDepartmentsView> UserDepartmentsViews { get; set; }
    }
}
