//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Llis.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDepartmentOperations
    {
        public int Id { get; set; }
        public int UserDepartmentId { get; set; }
        public int UserAccountId { get; set; }
        public string DepartmentId { get; set; }
        public string DesignationId { get; set; }
        public string Action { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
